### ISSUE TITLE
S3StatusErrorQuotaExceeded not listed as retryable.

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/libs3#12]
S3_status_is_retryable() does not list S3StatusErrorQuotaExceeded as a retryable error.

At least in the case of Oracle S3 this occurs when there are too many simultaneous requests which in that case would be retryable.  Maybe in others it wouldn't.

Consider adding this to the list.

**Comment by trel** [comment]
do we know anything more about this?

**Comment by JustinKyleJames** [comment]
I had a work-around for this in the S3 plugin but have now added this into the libs3 code.
