### ISSUE TITLE
Timeout when complete multipart upload takes a long time.

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/libs3#18]
When I upload a very large file (>30GiB) to a MinIO server on my machine, I am getting timeouts on complete multipart upload while MinIO is putting the parts together.  In my case it takes about 18 minutes to complete the multipart.  This is likely due to a non-production level MinIO server setup.

Nevertheless, this does indicate a need to allow the complete multipart operation longer to complete.

All of the libs3 operations have a timeout parameter (ms) which is passed directly to the CURLOPT_TIMEOUT_MS curl option.

However, there are two other settings that will cause a timeout in this scenario:  CURLOPT_LOW_SPEED_LIMIT and CURLOPT_LOW_SPEED_TIME.  The latter is set to 15 seconds in libs3.  Because complete multipart is not sending a lot of data in the response to the complete multipart (I believe it does send some spaces to keep alive) the data passed will be below the limit and the 15 second timeout will trigger.

To resolve this, I propose that the CURLOPT_LOW_SPEED* settings only be set if there is a non-zero timeout set.  (Zero means no timeout.)  So if there is no timeout set, use the low speed options to trigger a timeout.  If there is a timeout set, just use that timeout.

**Comment by trel** [comment]
this seems very defensible.     could easily PR it upstream later.

**Comment by JustinKyleJames** [comment]
The change has been implemented so closing this issue.
