### ISSUE TITLE
Libs3 changes to support deep archive

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/libs3#20]
This goes with irods/irods_resource_plugin_s3#2025

**Comment by alanking** [comment]
We don't need to put this in upstream or anything, right?

**Comment by trel** [comment]
Yes, eventually.  But we'd do it *from* the libs3 repo.

**Comment by alanking** [comment]
@JustinKyleJames - Is this done?

**Comment by alanking** [comment]
@JustinKyleJames - poke

**Comment by JustinKyleJames** [comment]
This has been implemented and will be closed.  Also, this project has been rolled into the S3 resource project.
