### ISSUE TITLE
Range is set improperly for S3_copy_object_range

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/libs3#5]
- [x] v4
- [x] master
-----

The end range for the following should be params->startByte + params->byteCount - 1.

Bytes in the middle are being written more than once and then it attempts to write one byte extra.

https://github.com/irods/libs3/blob/59b6237135126e53690a41a2baba74c092304c21/src/request.c#L399-L403

**Comment by trel** [comment]
this is the same as upstream  bji/libs3#102
