### ISSUE TITLE
S3_copy_object_range errors on x-amz-metadata-directive: REPLACE

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/libs3#6]
- [x] v4
- [x] master
-----

It seems to work if I comment the following out.

https://github.com/irods/libs3/blob/59b6237135126e53690a41a2baba74c092304c21/src/request.c#L405-L407

**Comment by trel** [comment]
This has been in the upstream libs3 since 2008 (and is still there) - so we probably should NOT remove it.

Need to understand what is erroring out.

**Comment by JustinKyleJames** [comment]
See the following issue.  https://github.com/bji/libs3/issues/80
