### ISSUE TITLE
Ceph S3 is complaining on range copy 

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/libs3#8]
When doing a range copy to Ceph S3, the server is complaining about not having the Content-Length header.  According to AWS documentation this header is not required.

Using AWS or Minio this works.

Look at updating libs3 to (conditionally?) add it.

```
> PUT <snip>/f2?partNumber=2&uploadId=<snip>
Host: <snip>
User-Agent: Mozilla/4.0 (Compatible; s3; libs3 4.1; Linux x86_64)
Accept: */*
Range: bytes=67108864-134217727
Authorization: <snip>
x-amz-date: 20201207T185949Z
x-amz-copy-source: <snip>/f1
x-amz-copy-source-range: bytes=67108864-134217727
x-amz-content-sha256: <snip>
Expect: 100-continue
^M
< HTTP/1.1 411 Length Required
< Content-Length: 278
< x-amz-request-id: <snip>
< Accept-Ranges: bytes
< Content-Type: application/xml

```

**Comment by JustinKyleJames** [comment]
To reproduce this, setup the S3 test scripts to use a Ceph S3 backend and run the following test:

python scripts/run_tests.py --run_s=test_irods_resource_plugin_s3.Test_S3_NoCache_V4.test_copy_file_greater_than_chunk_size

**Comment by trel** [comment]
support for Ceph is tested.   closing!
